import Head from "next/head";
import React from "react";
import Link from "next/link";
import LoginIcon from "@mui/icons-material/Login";
import HomeIcon from "@mui/icons-material/Home";
const Layout: React.FC = ({ children }: any) => {

  return (
    <>
      <Head>
        <title>TicTac</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossOrigin="anonymous"
        ></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="pos-f-t">
        <div className="collapse" id="navbarToggleExternalContent">
          <div className="bg-primary p-4">
            <h4 className="text-white">Collapsed content</h4>
            <span className="text-muted">Toggleable via the navbar brand.</span>
          </div>
        </div>
        <nav className="navbar navbar-expand-lg">
          <div className="container-fluid">
            <Link href="/" passHref={true}>
              <button
                className="btn btn-success"
                style={{ marginLeft: "1rem" }}
              >
                <HomeIcon />
              </button>
            </Link>

            <button
              className="navbar-toggler btn-light"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="nnavbarToggleExternalContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon"></span>
            </button>

            <div
              className="collapse navbar-collapse"
              id="navbarSupportedContent"
            ></div>
            <div className="indexPage">
              <form>
                <div className="row">
                  <div className="col">
                    <label>Identifiant :</label>
                    <input
                      type="email"
                      className="form-control"
                      id="exampleInputEmail1"
                      aria-describedby="emailHelp"
                      placeholder="LDAP:"
                    />
                  </div>
                  <div className="col">
                    <label>Mot de passe :</label>
                    <input
                      type="password"
                      id="exampleInputPassword1"
                      className="form-control"
                      placeholder="Mot De Passe :"
                    />
                  </div>{" "}
                  <button type="submit" className="btn btn-success ">
                    <LoginIcon />
                  </button>
                </div>
              </form>
            </div>
          </div>
        </nav>
        {children}
      </div>
    </>
  );
};
export default Layout;
