import { ObjectId } from "mongodb";
import type { NextApiRequest, NextApiResponse } from "next";
import { getDatabase } from "../../../src/database";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const mongodb = await getDatabase();
  const nom = req.body.nom;
  const prenom = req.body.prenom;
  const email = req.body.email;
  const profile = req.body.exampleRadios;
  const magasin = req.body.numeromagasin;
  const rayon = req.body.numerorayon;
  console.log(rayon);
  console.log(magasin);
  const matricule = Math.floor(Math.random() * 100000000);
  const newUser = {
    email: email,
    matricule: matricule,
    profile: profile,
  };
  const lookifalreadyhere = await mongodb
    .db()
    .collection("Users")
    .findOne({ email: email });
  if (lookifalreadyhere === null) {
    const addNewUser = await mongodb
      .db()
      .collection("Users")
      .insertOne(newUser)
      .then((id) => id.insertedId);

    const newSalaries = {
      idUser: addNewUser.toString(),
      nom: nom,
      prenom: prenom,
      droit_cp: 35,
      magasins: new ObjectId("62542ac959cf2086165f496e"),
      conges: [],
      horaires: [
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "02/01/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "03/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "04/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "05/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "06/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "07/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "08/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "09/01/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "10/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "11/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "12/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "13/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "14/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "15/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "16/01/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "17/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "18/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "19/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "20/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "21/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "22/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "23/01/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "24/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "25/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "26/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "27/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "28/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "29/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "30/01/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "31/01/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "01/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "02/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "03/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "04/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "05/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "06/02/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "07/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "08/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "09/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "10/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "11/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "12/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "13/02/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "14/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "15/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "16/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "17/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "18/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "19/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "20/02/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "21/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "22/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "23/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "24/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "25/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "26/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "27/02/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "28/02/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "01/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "02/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "03/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "04/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "05/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "06/03/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "07/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "08/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "09/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "10/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "11/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "12/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "13/03/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "14/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "15/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "16/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "17/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "18/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "19/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "20/03/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "21/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "22/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "23/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "24/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "25/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "26/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "27/03/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "28/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "29/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "30/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "31/03/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "01/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "02/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "03/04/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "04/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "05/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "06/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "07/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "08/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "09/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "10/04/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "11/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 8,
          },
          {
            designation: "mardi",
            date: "12/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 6,
          },
          {
            designation: "mercredi",
            date: "13/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "14/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: "",
            heure_realisees: "",
          },
          {
            designation: "vendredi",
            date: "15/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: "",
            heure_realisees: "",
          },
          {
            designation: "samedi",
            date: "16/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: "",
            heure_realisees: "",
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "17/04/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "18/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: "",
            heure_realisees: "",
          },
          {
            designation: "mardi",
            date: "19/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "20/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "21/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "22/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: "",
            heure_realisees: "",
          },
          {
            designation: "samedi",
            date: "23/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: "",
            heure_realisees: "",
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "24/04/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "25/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "26/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "27/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "28/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "29/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "30/04/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "01/05/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "02/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "03/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "04/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "05/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "06/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "07/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "08/05/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "09/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "10/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "11/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "12/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "13/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "14/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "15/05/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "16/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "17/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "18/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "19/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "20/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "21/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "22/05/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "23/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "24/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "25/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "26/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "27/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "28/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "29/05/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "30/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "31/05/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "01/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "02/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "03/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "04/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "05/06/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "06/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "07/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "08/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "09/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "10/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "11/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "12/06/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "13/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "14/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "15/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "16/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "17/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "18/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "19/06/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "20/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "21/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "22/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "23/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "24/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "25/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "26/06/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "27/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "28/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "29/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "30/06/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "01/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "02/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "03/07/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "04/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "05/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "06/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "07/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "08/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "09/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "10/07/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "11/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "12/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "13/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "14/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "15/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "16/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "17/07/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "18/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "19/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "20/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "21/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "22/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "23/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "24/07/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "25/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "26/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "27/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "28/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "29/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "30/07/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "31/07/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "01/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "02/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "03/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "04/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "05/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "06/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "07/08/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "08/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "09/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "10/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "11/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "12/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "13/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "14/08/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "15/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "16/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "17/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "18/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "19/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "20/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "21/08/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "22/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "23/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "24/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "25/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "26/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "27/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "28/08/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "29/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "30/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "31/08/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "01/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "02/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "03/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "04/09/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "05/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "06/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "07/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "08/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "09/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "10/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "11/09/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "12/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "13/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "14/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "15/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "16/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "17/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "18/09/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "19/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "20/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "21/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "22/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "23/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "24/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "25/09/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "26/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "27/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "28/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "29/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "30/09/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "01/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "02/10/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "03/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "04/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "05/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "06/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "07/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "08/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "09/10/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "10/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "11/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "12/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "13/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "14/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "15/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "16/10/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "17/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "18/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "19/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "20/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "21/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "22/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "23/10/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "24/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "25/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "26/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "27/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "28/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "29/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "30/10/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "31/10/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "01/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "02/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "03/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "04/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "05/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "06/11/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "07/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "08/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "09/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "10/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "11/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "12/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "13/11/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "14/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "15/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "16/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "17/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "18/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "19/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "20/11/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "21/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "22/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "23/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "24/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "25/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "26/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "27/11/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "28/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "29/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "30/11/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "01/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "02/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "03/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "04/12/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "05/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "06/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "07/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "08/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "09/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "10/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "11/12/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "12/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "13/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "14/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "15/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "16/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "17/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "18/12/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "19/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "20/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "21/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "22/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "23/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "24/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
        [
          {
            designation: "dimanche",
            regulariser: false,
            date: "25/12/2022",
            horaires: "",
            horaires_sup: 0,
            heure_necessaire: 0,
          },
          {
            designation: "lundi",
            date: "26/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mardi",
            date: "27/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "mercredi",
            date: "28/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "jeudi",
            date: "29/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "vendredi",
            date: "30/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
          {
            designation: "samedi",
            date: "31/12/2022",
            horaires: "",
            horaires_sup: 0,
            regulariser: false,
            heure_necessaire: 0,
          },
        ],
      ],
      profile: profile,
      img: "https://www.cabinet-nouvellefrance.fr/wp-content/uploads/2017/02/no-photo.png",
      soldes_cp: 0,
      rayon: "62542bb959cf2086165f496f",
      email: email,
      message: "",
    };

    const addNewCollabInMagasin = await mongodb
      .db()
      .collection("Collaborateurs")
      .insertOne(newSalaries);
    res.redirect(303, "/api/auth/login");
  } else {
    res.redirect(303, "/");
  }
}
